apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepilot-backend
  namespace: kubepilot
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
