apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubepilot-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ghanathey-Neelesh-Kumar/kubepilot-platform.git
    targetRevision: main
    path: k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: kubepilot-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
