apiVersion: v1
kind: Secret
metadata:
  name: kubepilot-db-secret
  namespace: kubepilot
  labels:
    app.kubernetes.io/name: kubepilot
    app.kubernetes.io/component: database-secret
type: Opaque
stringData:
  DB_USER: kubepilot
  DB_PASSWORD: kubepilot
  POSTGRES_USER: kubepilot
  POSTGRES_PASSWORD: kubepilot
  POSTGRES_DB: kubepilot
