apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubepilot-dev

resources:
- ../../base

patches:
- path: namespace-patch.yaml
- path: backend-replica-patch.yaml
- path: frontend-replica-patch.yaml
- path: backend-resource-patch.yaml
- path: frontend-resource-patch.yaml

images:
- name: kubepilot-backend
  newName: ghcr.io/ghanathey-neelesh-kumar/kubepilot-backend
  newTag: f979dfa
- name: kubepilot-frontend
  newName: ghcr.io/ghanathey-neelesh-kumar/kubepilot-frontend
  newTag: f979dfa
